### ISSUE TITLE
Styling the `Upload` button on profile apge

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-my#105]
On hovering the `Upload` button on profile page screen, cursor should change to pointer

Go to https://my.realdevsquad.com/profile
Browse an image from local system, hover on the `Upload` button and you'll understand that your cursor is not becoming a pointer

If you're confused, what's a cursor pointer, refer this doc: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by swarajpure** [comment]
More here: https://css-tricks.com/using-css-cursors/

**Comment by anshika29** [comment]
I ll take this up
