### ISSUE TITLE
Error: application.js:39 Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-my#205]
![image](https://user-images.githubusercontent.com/56217868/151829711-b0c1fee2-e8bf-4ba0-9661-7aace0ef7e8d.png)

Steps to reproduce;
1. Change the API endpoint to use staging API or local API (most like you won't get this error on production, figure out why later 😉)
2. Just start the frontend server and you should see this error in console

**Comment by MehulKChaudhari** [comment]
Hey Swaraj, I want to take this up.
