### ISSUE TITLE
Need a logout button

### ISSUE THREAD

**Issue by ivinayakg** [Real-Dev-Squad/website-my#237]
currently, when we click on the profile image it redirects you to "my" website of the RDS,  but not there or anywhere there is a logout button, sounds primitive but sometimes users can be skeptical of not logging out.

Maybe this is the immature experience of mine that I find this an issue, if so I would love your's thoughtful and valuable opinion on this which can further help me in understanding this.

**Comment by sunnykgupta** [comment]
>Maybe this is the immature experience of mine that I find this an issue...

You are perfectly right.

**Comment by satyam73** [comment]
Hello @rohan09-raj , please assign this issue to me.
