### ISSUE TITLE
Buttons/checkbox disabled if requirements not met

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-my#244]
All the buttons and checkboxes are enabled on the identity page, even if the requirements are not met. So disable them according to the requirements mentioned below:
- Save button for profile URL: enabled if there is a change in profile URL and not empty.
- Generate Chaincode: enabled if there is a profile URL.
- Checkbox: enabled if the user has a profile URL and chaincode in their user object.
- Link chaincode: enabled if the user has a profile URL and chaincode in their user object and the checkbox is checked.

**Comment by vinayak-trivedi** [comment]
Please assign this to me
