### ISSUE TITLE
make my site responsive

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/website-my#265]
currently, my site is not responsive, we need to make it responsive.

Images for reference

![image](https://user-images.githubusercontent.com/90315175/188370497-c6bc60f1-906d-44fe-a3ab-7b67cf7c02e5.png)
![image](https://user-images.githubusercontent.com/90315175/188928988-5f5cca6a-19c2-49e7-933a-ece49f13bee3.png)
![image](https://user-images.githubusercontent.com/90315175/188929119-53fc9318-29cb-4780-a363-b62dab6d8ae4.png)

**Comment by swapnadeepmohapatra** [comment]
Can you please assign me this issue?

**Comment by swapnadeepmohapatra** [comment]
Mobile:
![image](https://user-images.githubusercontent.com/41564532/188405606-e824dc7f-da8c-48ca-90ba-3ca7178dd728.png)

Desktop:
![image](https://user-images.githubusercontent.com/41564532/188405682-c03a5a37-8290-45ab-a7e2-ef6a161f7eb4.png)

Is this layout fine?
