### ISSUE TITLE
task percentagecompleted input getting hidden after we change percentage completed

### ISSUE THREAD

**Issue by vinayak-trivedi** [Real-Dev-Squad/website-my#272]
when we change the percentage of task completed, the slider which is used to update the task completed gets removed

video for reference⬇️

https://user-images.githubusercontent.com/90315175/190850303-ff4dfe9b-39c6-4215-8f6e-f2fa231223ba.mp4

**Comment by manish591** [comment]
Can I take this task?

**Comment by vinayak-trivedi** [comment]
> Can I take this task?

assigned to you @manish591
