### ISSUE TITLE
Make CSS Variables

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#308]
## Issue
- Currently we have different colors in a different file and we don't have any common colors to use
- Sometimes people use different shades for almost same colors
- Therefore, there is no consistency in the shades of colors

## Solution
- Make CSS variables of colors in file `variables.css` from all the CSS files
- Use that CSS variable in all the CSS files

**Comment by kush-x7** [comment]
Hey, I would love to do this task!
Please assign it to me
