### ISSUE TITLE
Put Notifications behind feature flag

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#314]
## Issue
- Currently notifications is a static route
- It has no connected backend which is a bad UX

## Solution
- Put the notifications route behind feature flag `dev=true`

**For example (also the expected behaviour) :**
- If you visit `https://my.realdevsquad.com`, the notifications route should not be visible in navigation menu as well as should not be accessible if user visits `https://my.realdevsquad.com/notification`
![image](https://user-images.githubusercontent.com/78433013/201584661-f9435e3a-ce87-4769-bd11-02b59ca4181b.png)

- But if the user put a flag `https://my.realdevsquad.com?dev=true`, the notifications route should be visible in the navigation menu and accessible  `https://my.realdevsquad.com/notifications?dev=true`

**Comment by vinit717** [comment]
Can you assign to me

**Comment by vinit717** [comment]
Can you please elaborate more about solution
