### ISSUE TITLE
Redesign the Profile Page

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#315]
## Issue
- The Profile route of the site is of no use
- It has a dumb form which cannot be used to update any data

## Points to Improve on
- Only preview the User Details of the logged in user
Reason : User can't update them through my-site, it will happen through the identity service they will deploy (for developers) and for others (they can maybe edit through my-site) - Depends on their role they have
- Maybe show their GitHub Profile, if they have
- Preview the Profile Picture and fix the UI of the Upload photo

## Current Profile Page
https://my.realdevsquad.com/profile

![image](https://user-images.githubusercontent.com/78433013/204078768-d3c71a9f-075d-4bac-a2d2-62ca06491e74.png)
![image](https://user-images.githubusercontent.com/78433013/204078775-b8ecb4ce-9f83-488e-aa4c-e254a3a014d4.png)

## Figma Design
https://www.figma.com/file/KdayucUZf6d6bZkOSogdY8/Profile-Page?node-id=0%3A1&t=lzPfvJYu9ni8eckT-1

**Comment by Maheima** [comment]
@rohan09-raj who is working on the figma design?

**Comment by rohan09-raj** [comment]
> @rohan09-raj who is working on the figma design?

@Maheima No one yet

**Comment by bhtibrewal** [comment]
I want to work on this @rohan09-raj
