### ISSUE TITLE
Step process for linking Profile Service to Identity Service

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-my#317]
## What is the issue?
We have an identity page on website-my through which we link our identity service to the user's profile service, it's functioning is fine but we want to make it a step process.

## Figma Design
https://www.figma.com/proto/xKTlVbkqJSd3wZKH3yAAEf/RDS_Onboarding?node-id=0%3A3&scaling=scale-down&page-id=0%3A1

## Explanation
We can detect which step the user is currently on by their user data.
- If the user has profileURL,, profileStatus and chaincode fields set to undefined, the user has never started the process, they are on the get started screen.
- If the user has some chaincode, that shows the user is on step 2, they generated the chaincode.
- If the user has chaincode and profileURL both, that shows the user is on step 3.
- ... and so on

## Discord Link Alternative
On the second last page, we don't have a way to generate a discord link as of now, so we can write there for the user to ask Ankush for the link and tell them that they verified their profile service.

## Tracking Issues
- [x] #352
- [ ] #353

**Comment by shreya-mishra** [comment]
I want to take this issue

**Comment by shreya-mishra** [comment]
@lakshayman do I need to make just a UI which is mentioned in figma ?

**Comment by rohan09-raj** [comment]
> @lakshayman do I need to make just a UI mentioned in Figma?

Yes, the functionality already exists, you have to create a new UI linked with the existing functionality.

**Comment by Dev-AkshatGupta** [comment]
Hey @rohan09-raj Can you assign this to me?
