### ISSUE TITLE
Integrated new Signup Flow

### ISSUE THREAD

**Issue by ivinayakg** [Real-Dev-Squad/website-my#322]
## Issue
When signing in with GitHub send the page href in query params as `&state=`
- RFC - https://github.com/Real-Dev-Squad/website-backend/issues/688

### Description
When you visit the `my-site` without login in, it will redirect you to github OAuth, but after login it redirects you back to `www-site` which is not what we want.

### Expected Flow
- User visits `my-site` for the first time without login.
- Now, they are redirected to the GitHub login page
- once the login is successful the user is expected to land back to the `my-site`
- Example PR - https://github.com/Real-Dev-Squad/website-www/pull/277

**Comment by Dev-AkshatGupta** [comment]
I want to work on it.
