### ISSUE TITLE
Create a 404 Page

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#324]
## Points to remember
- For reference - https://members.realdevsquad.com/x
- Navbar should be there navigate across the pages
- Footer can also be there.
- For visiting every route of `https://my.realdevsquad.com/` which doesn't exist redirect to this 404 page
- Please direct the user to this 404 route here
https://github.com/Real-Dev-Squad/website-my/blob/327dc1588709cb48a52974be3f87a5bf273b79de/app/routes/notifications.js#L15

## Image to Use
![page-not-found](https://user-images.githubusercontent.com/78433013/205073331-4ee78343-6dd9-4d49-9888-c8114ae35ab1.png)

**Comment by ranitasahaa1230** [comment]
I want to work on this task. Could you please assign this to me, @rohan09-raj  ?

**Comment by satyam73** [comment]
Hello @rohan09-raj you can assign me this issue.
