### ISSUE TITLE
Dropdown click not working correctly

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#326]
## Description
- On Clicking any of the navigation dropdown items, the click only works on the text
- It is not working on the whole item.

## Image Reference
![image](https://user-images.githubusercontent.com/78433013/205295968-7253e430-32e0-4277-b170-14d402dafcaa.png)

**Comment by satyam73** [comment]
Hello @rohan09-raj please assign me this issue, I want to work on this.
