### ISSUE TITLE
Fix the Page Title

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#348]
## What to do?
- Update the page title from `My` to `My | Real Dev Squad`
![image](https://user-images.githubusercontent.com/78433013/211266165-7965ed5f-ead1-4c93-aeea-c33baf748fd9.png)
- Remove the title tag from `index.html` **Reason :** It conflicts with Ember Handlebars {{page-title "TITLE"}}

**Comment by srejitk** [comment]
Hey!

I can take it up
