### ISSUE TITLE
Converting the Unique token ID to QR code 

### ISSUE THREAD

**Issue by shreya-mishra** [Real-Dev-Squad/website-my#360]
**Refer Doc:** 
https://docs.google.com/document/d/1HN09crzvnkk_URwm6qi-fe17PGiqzogvigeRG5bu5iI/edit?usp=sharing

**Related Issue**
https://github.com/Real-Dev-Squad/website-my/issues/361

**Comment by SHREYASH96OG** [comment]
You can create QR code By Use of Python and it's library
You have first install python and libraries

- pip install pyqrcode
- pip install pypng

**Code main.py**
# Import QRCode from pyqrcode
import pyqrcode
import png
from pyqrcode import QRCode


# String which represents the QR code
s = input("Enter the Token")

# Generate QR code
url = pyqrcode.create(s)


url.svg("myqr.svg", scale = 8)
url.png('myqr.png', scale = 6)

**O/P**
![screen](https://user-images.githubusercontent.com/96031865/222479021-00bc75ce-9ab2-458b-9aca-52a1d6c1d121.png)
