### ISSUE TITLE
Setup staging for my-site

### ISSUE THREAD

**Issue by rohan09-raj** [Real-Dev-Squad/website-my#365]
## Note
- The below method is which I follow, if there is any another method to add CNAME or deployment within the existing project, you can go ahead with it.

## Steps to follow
- Go to Cloudflare Pages
- Create a project for `develop` branch of my-site
- Fill the details as per the screenshot

#### Build Command
```
ember build --environment=staging
```
![image](https://user-images.githubusercontent.com/78433013/222929006-839a15b8-363a-46b3-8251-b4261dfe724f.png)
- `Save and deploy`

### Deployment is successful 🎉 🥳 

- Add a `CNAME`
```
staging-my
```
- Add the target to the deployed URL
- Wohoo 🎉 , test the deployed staging my-site on https://staging-my.realdevsquad.com

**Comment by ankushdharkar** [comment]
Got the staging site deployed on Netlify. 🎉 

More details here: https://discord.com/channels/673083527624916993/781622711436050463/1081805567808524399
