### ISSUE TITLE
Instagram id field missing in the signup form

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-my#41]
Instagram id field is missing on the [signup form](https://my.realdevsquad.com/signup)

Just check `@tracked fields` inside `app/controllers/signup.js` and you'll understand what is to be done 😉

**Comment by TD-17** [comment]
> Instagram id field is missing on the [signup form](https://my.realdevsquad.com/signup)
> 
> Just check `@tracked fields` inside `app/controllers/signup.js` and you'll understand what is to be done 😉

Can I work on this ?

**Comment by swarajpure** [comment]
> 
> 
> > Instagram id field is missing on the [signup form](https://my.realdevsquad.com/signup)
> > Just check `@tracked fields` inside `app/controllers/signup.js` and you'll understand what is to be done 😉
> 
> Can I work on this ?

Sure. Assigning you 😄
