### ISSUE TITLE
Remove the user action of marking user IDLE

### ISSUE THREAD

**Issue by manish591** [Real-Dev-Squad/website-my#412]
### Issue

We want to automatically mark the user's IDLE and not by user action on my site.
For more information refer to this issue [here](https://github.com/Real-Dev-Squad/todo-action-items/issues/155)

### Current Process

Users can update their status on my site by clicking the `Change your status to the IDLE` button.

![Screenshot (64)](https://github.com/Real-Dev-Squad/website-my/assets/79859472/70a8685b-247d-4ec7-aed1-83bea81344db)

### Changes Required

We want to remove the button `change your status to idle` and the action associated with it. 
We will display the user's idle status based on whether they're assigned any In progress task or not automatically.

**Comment by heyrandhir** [comment]
Since the backend changes were not incorporated we will be closing this PR
