### ISSUE TITLE
Enable cancel OOO 

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/website-my#495]
### Requirement:
Introduce a "Cancel Out of Office" button to allow users who are currently set to "Out of Office" (OOO) to return to work before the designated out-of-office period concludes.

### Acceptance Criteria:

- [ ] The "Cancel Out of Office" button must be prominently displayed on the user interface when a user is in an "Out of Office" state.
- [ ] Clicking the "Cancel Out of Office" button should initiate a PATCH request to the API endpoint /users/status/self.
- [ ] The PATCH request should include a request body with the key-value pair { cancelOoo: true }.
- [ ] Upon successful cancellation, the user's status should immediately change from "Out of Office" to "Active" or "Idle".
- [ ] The button should disappear or become inactive once the user's status has been successfully updated.
- [ ] The system should not allow users to cancel their "Out of Office" status if they are already in an "Active" or Idle status.
- [ ] Proper error handling should be implemented in case the API request fails, providing informative feedback to the user.
- [ ] Thoroughly test the feature to ensure its reliability and that it adheres to the specified behavior
- [ ] Document the implementation details.
- [ ] Conduct user testing and gather feedback to make any necessary improvements based on user experience.

**Comment by PeeyushPrashant** [comment]
I want to work on this task
