### ISSUE TITLE
Make `lint` script work for all the operating systems

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-my#51]
Currently our `lint` script doesn't work on Windows, but works fine on Linux and MacOS.

Once the `lint` starts working for these operating systems, we could add linting in pre-commit hooks (not a part of this issue though). Refer issue #10

**Comment by rkmr039** [comment]
I will start analysis and do the needful

**Comment by swarajpure** [comment]
> 
> 
> I will start analysis and do the needful

Sounds great! Assigning this issue to you.
