### ISSUE TITLE
Identity page - Responsiveness

### ISSUE THREAD

**Issue by lakshayman** [Real-Dev-Squad/website-my#565]
### Issue Description
The identity page is giving issues on some screen sizes. We want to make it responsive and look good on all screen sizes.

### Expected Behavior
Should be responsive on all screen sizes.

### Current Behavior
Currently, giving issues with screens with smaller heights.

### Screenshots
![image](https://github.com/Real-Dev-Squad/website-my/assets/45519620/296b1d03-f145-4bfe-8bb6-b476164624c8)
![image1](https://github.com/Real-Dev-Squad/website-my/assets/45519620/9917a3c1-ccbe-4851-8ef6-23d7ba151594)

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist
- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by ojas-elawadhi** [comment]
Can I take this issue?
