### ISSUE TITLE
[BUG] Image upload modal not  visible completely

### ISSUE THREAD

**Issue by tejaskh3** [Real-Dev-Squad/website-my#618]
### Issue Description
The close button for **image update message modal** is behind the navbar, and there is shifting of content also, either make the container small or bring the close button above the navbar that is increase z-indexing.

### Expected Behavior
The modal should be visible, but upper part of modal is behind the navbar.

### Current Behavior
The close button is not visible on the modal.

https://github.com/user-attachments/assets/5e6e0a63-447e-4147-92ce-e80d0605f910

### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. Go to [my site](https://my.realdevsquad.com/profile?dev=true)
2.  Try changing your profile photo
3. After successfully updating/uploading your profile picture scroll down you will see the closing button of success modal is behind navbar 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [x] Low

### Checklist

- [x] I have read and followed the project's code of conduct.
- [x] I have searched for similar issues before creating this one.
- [x] I have provided all the necessary information to understand and reproduce the issue.
- [x] I am willing to contribute to the resolution of this issue.

**Comment by mdansarijaved** [comment]
@tejaskh3 @yesyash  @vinit717 My TCR have been approved for this task.

**Comment by mdansarijaved** [comment]
under the dev=true flag there is "use mobile app" dialog which also have the same issue.
![image](https://github.com/user-attachments/assets/8d94f311-4082-4900-8ccb-66da17e9ce37)

**Comment by mdansarijaved** [comment]
@tejaskh3 @yesyash I had some questions will these changes go under dev=true flag ?? and do I need to write test cases for these too?
