### ISSUE TITLE
Should be sending `company` in signup form

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-my#63]
We should be sending `company` in signup form than `company_name`

**Comment by swarajpure** [comment]
Some of the places we've used `company_name` instead of `company` and we're also sending `company_name` the `PATCH users/self` call. We should be using `company` everywhere

Changes to be done in this file: https://github.com/Real-Dev-Squad/website-my/blob/develop/app/controllers/signup.js

**Comment by Devashish0210** [comment]
I'll handle this. 😄

**Comment by swarajpure** [comment]
> I'll handle this. smile

Assigned to you! 🚀
