### ISSUE TITLE
Human readable date for the task

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-my#89]
Render human readable date (like `8 days later (22 May)`), instead of the milliseconds since epoch value

![image](https://user-images.githubusercontent.com/1935403/118296396-c6976400-b491-11eb-8387-4dfd616875ff.png)

**Comment by jv18creator** [comment]
Hi there
I am new at contributing and I would like to work on this issue.
How can I do that?

**Comment by ankushdharkar** [comment]
Hi @jv18creator,
Do you want to work on EmberJS?

**Comment by jv18creator** [comment]
No, I thought I could solve this with vanillaJS, didn't knew about EmberJS.

**Comment by ankushdharkar** [comment]
@jv18creator Why let that stop you? This is a good opportunity to learn something new and grow your boundaries

**Comment by ankushdharkar** [comment]
@jv18creator You should join our Discord server: https://discord.gg/FGBkbsND
We have more tasks that you can pick up. Check out realdevsquad.com

**Comment by ankushdharkar** [comment]
@jv18creator You should join our Discord server: https://discord.gg/FGBkbsND
We have more tasks that you can pick up. Check out the apps we are building at https://realdevsquad.com

**Comment by jv18creator** [comment]
> @jv18creator You should join our Discord server: https://discord.gg/FGBkbsND
> We have more tasks that you can pick up. Check out the apps we are building at https://realdevsquad.com

Just joined your discord server thanks for the invitation.

**Comment by KhushalAbrol** [comment]
I want to work on this issue. Though I don't know emberJs, I can try. But please tell me where I can find it on site I am not able to find it.
