### ISSUE TITLE
Issue with footer

### ISSUE THREAD

**Issue by swarajpure** [Real-Dev-Squad/website-my#99]
If we pull the devtools window (the one which we get by clicking `inspect element`) all the way up, we see this problem:
![image](https://user-images.githubusercontent.com/56217868/123278588-b0ff6a80-d524-11eb-87e6-35813cb681a3.png)

The footer should behave like the way it is behaving here: https://status.realdevsquad.com/

**Comment by himanshukm2301** [comment]
I'll take this up.
